### ISSUE TITLE
http://eden.sahanafoundation.org/ is inaccesible

### ISSUE THREAD

**Issue by tuanta** [sahana/eden-legacy#1592]
The site http://eden.sahanafoundation.org/ (a Trac instance) has been inaccessible for weeks (at least) with error message:
"
Trac Error
TracError: Unable to check for upgrade of trac.db.api.DatabaseManager: OperationalError: database is locked
"
Anyone can check?

**Comment by flavour** [comment]
Server brought back.
NB Mailing List probably better place to report than GitHub Issues

**Comment by tuanta** [comment]
> Server brought back.

Thanks.

> NB Mailing List probably better place to report than GitHub Issues

Sure, I will join. Very long time no see you, Fran.
